In [ ]:
import pandas as pd
from boruta import BorutaPy
from sklearn.ensemble import RandomForestRegressor

In [4]:
df = pd.read_csv("../datasets/energydata_complete.csv")
df["date"] = pd.to_datetime(df["date"])
df["Appliances"] = pd.to_numeric(df["Appliances"])
df.set_index("date", inplace=True)
df

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
date,,,,,,,,,,,,,,,,,,,,,
2016-01-11 17:00:00,60,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
2016-01-11 17:10:00,60,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2016-01-11 17:20:00,50,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
2016-01-11 17:30:00,50,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,...,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000,45.410389,45.410389
2016-01-11 17:40:00,60,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,...,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [14]:
X = df.iloc[:,1:-2]
y = df.Appliances
X

,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T8,RH_8,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint
date,,,,,,,,,,,,,,,,,,,,,
2016-01-11 17:00:00,30,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,18.2000,48.900000,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000
2016-01-11 17:10:00,30,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,18.2000,48.863333,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000
2016-01-11 17:20:00,30,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,18.2000,48.730000,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000
2016-01-11 17:30:00,40,19.890000,46.066667,19.200000,44.590000,19.790000,45.000000,18.890000,45.723333,17.166667,...,18.1000,48.590000,17.000000,45.4000,6.250000,733.8,92.000000,6.000000,51.500000,5.000000
2016-01-11 17:40:00,40,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,18.1000,48.590000,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-05-27 17:20:00,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,24.7000,50.074000,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333
2016-05-27 17:30:00,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.700000,45.590000,23.230000,...,24.7000,49.790000,23.200000,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000
2016-05-27 17:40:00,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,24.7000,49.660000,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667
2016-05-27 17:50:00,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,24.6625,49.518750,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333
2016-05-27 18:00:00,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,24.7360,49.736000,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000

In [9]:
rf = RandomForestRegressor(n_jobs=-1, max_depth=7, random_state=1337)
feat_selector = BorutaPy(rf, n_estimators='auto', verbose=2, random_state=1337)

In [15]:
feat_selector.fit(X, y)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	25
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	20
Tentative: 	5
Rejected: 	0
Iteration: 	9 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	10 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	11 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	12 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	13 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	14 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	15 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	16 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	17 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	18 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	19 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	20 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	21 / 100
Confirmed: 	20
Tentative: 	4
Rejected: 	1
Iteration: 	22 / 100
Confirmed: 	21
Tentative: 	3
Rejected: 	1
Iteration: 	23 / 100
Confirmed: 	21
Tentative: 	3
Rejected: 	1
Iteration: 	24 / 100
Confirmed: 	21
Tentative: 	3
Rejected: 	1
Iteration: 	25 / 100
Confirmed: 	21
Tentative: 	3
Rejected: 	1
Iteration: 	26 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	27 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	28 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	29 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	30 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	31 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	32 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	33 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	34 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	35 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	36 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	37 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	38 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	39 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	40 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	41 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	42 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	43 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	44 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	45 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	46 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	47 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	48 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	49 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	50 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	51 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	52 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	53 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	54 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	55 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	56 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	57 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	58 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	59 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	60 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	61 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	62 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	63 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	64 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	65 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	66 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	67 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	68 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	69 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	70 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	71 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	72 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	73 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	74 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	75 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	76 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	77 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	78 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	79 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	80 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	81 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	82 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	83 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	84 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	85 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	86 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	87 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	88 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	89 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	90 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	91 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	92 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	93 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	94 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	95 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	96 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	97 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	98 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1
Iteration: 	99 / 100
Confirmed: 	22
Tentative: 	2
Rejected: 	1


BorutaPy finished running.

Iteration: 	100 / 100
Confirmed: 	22
Tentative: 	0
Rejected: 	3

BorutaPy(estimator=RandomForestRegressor(max_depth=7, n_estimators=98,
                                         n_jobs=-1,
                                         random_state=RandomState(MT19937) at 0x7554DA690740),
         n_estimators='auto',
         random_state=RandomState(MT19937) at 0x7554DA690740, verbose=2)

In [17]:
feat_selector.support_

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True, False, False])

In [18]:
feat_selector.ranking_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 4, 3])